#PBS -N ed_df
#PBS -l nodes=1:gpus=1:s
#PBS -o /gdata/liyh/data/CelebA/checkpoint/ed_df/inference_out_file.out
#PBS -e /gdata/liyh/data/CelebA/checkpoint/ed_df/inference_err_file.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/p2p/ -s /gdata/liyh/project/p2p/summit/inference/ed_df/train.sh bit:5000/deepo 