#PBS -N hd_exp-0004_finetune_sa_last2
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0004/hd_exp-0004_finetune_sa_last2.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0004/hd_exp-0004_finetune_sa_last2.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0004/train.sh bit:5000/pengll_tf1.8.4_python3.6-tk 

echo "0004_finetune_sa_last2" 
echo "commit e6b90b3aa29569c7af908db44a48d66e3f370263"
