#PBS -N hd_exp-0004_finetune_sa_mru
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0004/hd_exp-0004_finetune_sa_mru.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0004/hd_exp-0004_finetune_sa_mru.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

echo "0004_finetune_sa_mru" 
echo "commit dce62f15abc1d8e52724cc9c51b9b82a5cd4ea02"

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0004/train.sh bit:5000/pengll_tf1.8.4_python3.6-tk 

