#PBS -N no_offset_mru_df_d
#PBS -l nodes=1:gpus=2:d
#PBS -o /gdata/liyh/data/CelebA/checkpoint/no_offset/mru_df_s/out_file.out
#PBS -e /gdata/liyh/data/CelebA/checkpoint/no_offset/mru_df_s/err_file.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/p2p/ -s /gdata/liyh/project/p2p/summit/no_offset/mru_df/train.sh bit:5000/deepo_9 