#PBS -N hd_exp-0003_p2p
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0003/hd_exp-0003_p2p.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0003/hd_exp-0003_p2p.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

echo "0003_p2p" 
echo "commit 5b785cf629209afdfe0e52dee4dfc39d0eb19f0f"

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0003/train_p2p.sh bit:5000/pengll_tf1.8.4_python3.6-tk 


