#PBS -N hd_exp-0003_mru_NoFM_NoS_NoG
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0003/hd_exp-0003_mru_NoFM_NoS_NoG.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0003/hd_exp-0003_mru_NoFM_NoS_NoG.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0003/train_mru_res.sh bit:5000/pengll_tf1.8.4_python3.6-tk 

echo "0003_256_D_cut_NoGlobalD" 
echo "commit 3a164a681760c430286a81cf7633ebc5c08eecf5"