#PBS -N hd_exp-0003_256_D
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0002/hd_exp-0003_256_D.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0002/hd_exp-0003_256_D.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0003/train_256_D.sh bit:5000/pengll_tf1.8.4_python3.6-tk 

echo "baseline, lsgan, fm, style, " 
echo "commit c834bbb7ba6dcb8962ffaa7dec68a0a1d746d0a0 \
Author: lyhangustc <lyh9001@mail.ustc.edu.cn> \
Date:   Sun Mar 31 22:01:29 2019 +0800 \
update"