#PBS -N exp-0004
#PBS -l nodes=1:gpus=4:Q
#PBS -o /gdata/liyh/project/e2p/summit/resgan/exp-0004/out_file.out
#PBS -e /gdata/liyh/project/e2p/summit/resgan/exp-0004/err_file.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/resgan/exp-0004/train.sh bit:5000/pengll_tf1.8.4_python3.6-tk 