#PBS -N hd_exp-0002_Nolsgan_NoStyle_NoFM_weight_100_1_10_10
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0002/hd_exp-0002_Nolsgan_NoStyle_NoFM_weight_100_1_10_10.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0002/hd_exp-0002_Nolsgan_NoStyle_NoFM_weight_100_1_10_10.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0002/train_weight.sh bit:5000/pengll_tf1.8.4_python3.6-tk 

echo "baseline, wgan, fm, style, weight: l1_gan_fm_style, 0002_Nolsgan_NoStyle_NoFM_weight_100_1_10_10