#PBS -N compute_KID
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0006/compute_KID.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0006/compute_KID.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

echo "compute_KID" 
echo "commit 6dac0650c76449aa2037c2de884bbc3952c64a7b"

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0006/compute_KID.sh bit:5000/pengll_tf1.8.4_python3.6-tk 