#PBS -N test_exp-0004_finetune_sa_last2_end_dgx
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0005/test_exp-0004_finetune_sa_last2_end_dgx.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0005/test_exp-0004_finetune_sa_last2_end_dgx.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

echo "test_exp-0004_finetune_sa_last2_end_dgx" 
echo "commit 358cfef26a006cd8c0e622c4a991d544a26bcc29"

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0005/test_exp-0004_finetune_sa_last2_end_dgx.sh bit:5000/pengll_tf1.8.4_python3.6-tk 