#PBS -N test_exp-0003_p2p
#PBS -l nodes=1:gpus=2:D
#PBS -o /gdata/liyh/project/e2p/summit/hd/exp-0005/test_exp-0003_p2p.out
#PBS -e /gdata/liyh/project/e2p/summit/hd/exp-0005/test_exp-0003_p2p.err
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo This job runs on following nodes:
cat $PBS_NODEFILE
cat $PBS_GPUFILE

echo "test_exp-0003_p2p" 
echo "commit 7a05e688a65f548d15cc78d3ab606b78dd8c2bec"

startdocker  -D /gdata/liyh/ -P /gdata/liyh/project/e2p/ -s /gdata/liyh/project/e2p/summit/hd/exp-0005/test.sh bit:5000/pengll_tf1.8.4_python3.6-tk 